Exchange/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.homePageView, name='homepage'),
    path('order/<int:id>/', views.orderView, name='order'),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.loginPageView, name='login'),
    path('register/', views.registerPageView, name='register'),
    path('account/<int:id>/', views.accountPageView, name='account'),
    path('logout/', views.logoutUser, name='logout'),
]

templates/partials/_navbar.html
<nav class="navbar">

    <div class="navElem">
        <a class="logo" href="{% url 'app:homepage' %}">
            {% load static %}
            <img src="{% static 'img/logo.png' %}" alt="" width="40px" class="img">
            BTC Exchange
        </a>
    </div>

    <div class="navElem">
        <a href="{% url 'app:homepage' %}">
            <span class="central" > Home </span>
        </a>
        <a href="{% url 'app:order' user.id %}">
            <span class="central" > Exchange </span>
        </a>

        <a href="{% url 'user:account' user.id %}">
            <span class="central" > Account </span>
        </a>
    </div>

    <!-- Sezione a destra della navbar che mostra username e permette il logout -->
    <div class="navElem">
        <span class="hello-msg">
            <span>Hello, </span>
            <a href="{% url 'user:account' user.id %}">
                <span> {{request.user}}</span>
            </a>
        </span>
        <span style="font-weight: 100; font-style: italic;"> <a href="{% url 'user:logout' %}">Logout</a></span>
    </div>

</nav>