Exchange/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.homePageView, name='homepage'),
    path('order/<int:id>/', views.orderView, name='order'),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.loginPageView, name='login'),
    path('register/', views.registerPageView, name='register'),
    path('account/<int:id>/', views.accountPageView, name='account'),
    path('logout/', views.logoutUser, name='logout'),
]

user/models.py
from django.db import models

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Form for the user registration
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from app.decorators import unauthenticated_user, allowed_users
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import json
import random
# From this app
from .forms import NewUserForm
# From other app
from app.models import Wallet, Profile
from app.market import Market

# Register page's view
@unauthenticated_user
@csrf_exempt
def registerPageView(request):
    data = Market()
    currency = data.updated_data()

    form = NewUserForm()
    if request.method == 'POST':
        
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Profile creation
            newUserProfile = Profile(
                user=user,
            )
            newUserProfile.save()

            #Wallet Creation
            newUserWallet=Wallet(
                user=user,
                btcWallet = round(random.uniform(1, 10), 8),
                usdWallet = round(random.uniform(50000, 150000), 2),
            )
            
            newUserWallet.startValue = newUserWallet.usdWallet + (newUserWallet.btcWallet*currency)
            newUserWallet.save()

            return redirect('user:login')
        else:
            messages.info(request, 'Check that you have filled in all the required fields correctly.')

    return render(request, 'user/register.html', {"form": form})

# Login page's view
@unauthenticated_user
@csrf_exempt
def loginPageView(request):
    form = AuthenticationForm(request, data=request.POST)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('app:homepage')
        else:
            messages.info(request, 'Wrong username or password')

    return render(request, 'user/login.html', {"loginForm": form})

# Account page's view
@login_required(login_url='login')
@csrf_exempt
def accountPageView(request, id):
    data = Market()
    currency = data.updated_data()

    username = request.user.username

    userWallet = get_object_or_404(Wallet, user_id=id)

    btcBalance = userWallet.btcWallet
    usdBalance = userWallet.usdWallet

    actualValue = usdBalance + (btcBalance * currency)
    startValue = userWallet.startValue
    
    delta = actualValue - startValue

    return render(request, 'user/account.html', {
        'username': username, 
        'delta': delta,
        'btcBalance': btcBalance,
        'usdBalance': usdBalance
        })

# Logout view
@csrf_exempt
def logoutUser(request):
    logout(request)
    return redirect('user:login')

user/templates/user/account.html
{% extends "base.html" %}
{% block content %}

{% block _navbar %}
{% include "partials/_navbar.html" %}
{% endblock _navbar %}

<section class="sectionNav">
    <div class="accountPageContainer">
        <h1>Account Dashboard</h1>
        <div class="card">

            <div class="profilePic">
                <label class="-label" for="file">
                    <span class="glyphicon glyphicon-camera"></span>
                    <span>Change Image</span>
                </label>
                <input id="file" type="file" onchange="loadFile(event)" />
                {% load static %}
                <img src="{% static '/img/small-profile.jpeg' %}" id="output" width="200" />
            </div>

            <div class="info">
                <h2>Hello {{username}},</h2>
                {% if delta >= 0 %}
                <p>The value of your portfolio compared to the creation date increased by {{delta|stringformat:".2f"}}$</p>
                {% else %}
                <p>The value of your portfolio compared to the creation date decreased by {{delta|stringformat:".2f"}}$ </p>
                {% endif %}
            </div>
        </div>

        <div class="cardWallet">

            <h2>Wallet</h2>

            <div class="tableContainer">
                <table class="gridBalance">
                    
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        <tr>
                            <td>
                                <span><img src="{% static '/img/logoUsd.png' %}" alt="usd logo" width="30px"></span>
                                <span>USD</span>
                            </td>
                            <td>{{ usdBalance }}</td>
                        </tr>
                        <tr>
                            <td>
                                <span><img src="{% static '/img/logo.png' %}" alt="btc logo" width="30px"></span>
                                <span>BTC</span>
                            </td>
                            <td>{{ btcBalance }}</td>
                        </tr>
                    </tbody>
                    
                </table>
            </div>

        </div>

    </div>
</section>

<script>
    var loadFile = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

{% endblock %}

user/templates/user/login.html
{% extends "base.html" %}
{% block content %}

<h1>Sign In</h1>
<section class="centerScreenSection">
  <form method="POST" class="cardCenter">
    {% csrf_token %}
    {{ loginForm }}
    <a>
      <input type="submit" value="Log in">
    </a>
  </form>

  {% for message in messages %}
      <p id="messages">{{message}}</p>
  {% endfor %}
  <p> Don't have an account yet? <a href="{% url 'user:register' %}" style="color: #ff9416;"> Sign up!</a></p>

</section>

{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}
{% block content %}

<h1>Sign Up</h1>
<section class="centerScreenSection">
    <div >
        <div >
            <form action="#" method="post" class="cardCenter">
                {% csrf_token %}
                {{form}}
                <div >
                    <label >
                        <input type="checkbox" class="checkbox" required="">
                        <span>I agree to the Terms and Conditions</span>
                    </label>
                    <div class="clear"> </div>
                </div>
                <input type="submit" value="SIGN UP">
            </form>
            
            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}

            <p> Already have an account? <a href="{% url 'user:login' %}" style="color: #ff9416;"> Sign in!</a></p>
        </div>
    </div>
</section>

{% endblock %}